### PR TITLE
Make default_key_name optional

### LINKED ISSUE #128: Make AWS keypair optional
Currently, the cpi [requires the name of a key pair in EC2](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/master/jobs/aws_cpi/spec#L32-L34).
AWS also does not require this key pair, and we can tell BOSH isn't leveraging it (because it doesn't ask for the private key ever), so there's no need for it. Including one represents a minor security concern, because it's one more access key to rotate or that could get lost. 
We'd like to remove this as a required field if at all possible

### PR DESCRIPTION
**Pull request by bengerman13**
AWS does not require keypair, and omitting it is better aligned with security best-practices in most cases.

Note that I updated the unit tests, and they pass, but the integration tests mention they rely on the keypair, so I didn't try to add a test case there.

fixes #128

### CODE REVIEW

**Comment by bengerman13** [comment]
Thank @rkoster  - I'm working on it. My org has (had?) a CLA previously, but EasyCLA isn't letting me through, so I'm opening a ticket with them

**Comment by bengerman13** [comment]
@rkoster - looks like I finally got through the CLA process

**Review by ramonskie — APPROVED** [review]
LGTM

**Review by rkoster — APPROVED** [review]
LGTM

**Comment by rkoster** [comment]
Thanks! @bengerman13

**Pull request merged**
